# fly.toml app configuration file generated for lessonlinx on 2023-11-21T10:41:27-06:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "lessonlinx"
primary_region = "ord"
console_command = "/rails/bin/rails console"

[build]

[deploy]
  release_command = "./bin/rails db:prepare db:seed"
  

[processes]
  app = "./bin/rails server"
  sidekiq = "bundle exec sidekiq -C config/schedule.yml"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[statics]]
  guest_path = "/rails/public"
  url_prefix = "/"
